version: '3.8'
services:
  puppet_os_arm64:
    image: piper:humble-amd64
    platform: linux/amd64
    container_name: piper
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - ROS_NAMESPACE=${PUPPET_ID}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /sys/class/net:/sys/class/net:rw  # Add CAN interface access
      - /sys/devices:/sys/devices:rw       # Modified this line for USB/PCI devices
    privileged: true
    network_mode: "host"  # Important for CAN interfaces
    cap_add:
      - NET_ADMIN  # Required for CAN interface configuration
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/dri:/dev/dri
    restart: unless-stopped
    ports:
      - "8765:8765"  # Foxglove
      - "2222:22"    # SSH
