[supervisord]
nodaemon=true

# Enable supervisorctl to query and control running programs via a
# Unix-domain socket. This adds the commands `docker exec piper
# supervisorctl status` (default path) or `supervisorctl -c
# /etc/supervisor/conf.d/supervisord.conf status`.
[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
stderr_logfile=/var/log/sshd.err.log
stdout_logfile=/var/log/sshd.out.log

[program:rosbridge]
command=/bin/bash -c "source /opt/ros/humble/setup.bash && source /app/ros2_ws/install/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
autorestart=true
stderr_logfile=/var/log/rosbridge.err.log
stdout_logfile=/var/log/rosbridge.out.log

[program:chronyd]
command=/usr/sbin/chronyd -d -n -f /etc/chrony/chrony.conf
# -d enables debugging, -n prevents forking, -f specifies config file
autorestart=true
stderr_logfile=/var/log/chronyd.err.log
stdout_logfile=/var/log/chronyd.out.log

